### ISSUE TITLE
Wrong acronym in french translation of the kubernetes walkthrough page

### ISSUE THREAD

**Issue by Salicorne** [MicrosoftDocs/azure-docs.fr-fr#677]
Hello, 
I think there is an issue with the french translation of the page https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough#create-aks-cluster : the title "Create AKS cluster" is translated in "Créer un cluster ACS". This acronym may refer to Azure Cloud Shell (presented earlier in the page) but the cluster is really AKS, as confirmed by the first sentence bellow (Utilisez la commande az aks create pour créer un cluster AKS). 
The same typo is repeated at the bottom of this page and several others, in the "next steps" section : "Pour en savoir plus sur ACS et parcourir le code complet de l’exemple de déploiement, passez au tutoriel sur le cluster Kubernetes." 
Apart from that the documentation is great, thank you for maintaining it ! 

EDIT : I realized ACS may also refer to Azure Container Service
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6115d555-45a1-6539-4af6-fbc20a99f008
* Version Independent ID: 21f80c83-ba10-9b7e-c54f-51a9c140517c
* Content: [Démarrage rapide : Déployer un cluster Azure Kubernetes Service](https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough#feedback)
* Content Source: [articles/aks/kubernetes-walkthrough.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/kubernetes-walkthrough.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @Salicorne
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Salicorne,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pageshttps://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough#feedback  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,

Microsoft DOCS International Team

**Comment by Salicorne** [comment]
This is great, thank you ! 
The typo is however still present in the bottom section of https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough-portal#next-steps and https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough-rm-template#next-steps (Pour en savoir plus sur ~~ACS~~ AKS et parcourir le code complet de l’exemple de déploiement, passez au tutoriel sur le cluster Kubernetes.)
Best regards
